name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - v*
  pull_request:
    branches: [ "master" ]
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: ls
      run: echo $(ls)
    - name: Login in docker
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build the Docker image
      run: docker build -t gridorius/bitrix-env:latest -t gridorius/bitrix-env:${{github.ref_name}} .
    - name: Push docker image
      run: |
        docker push gridorius/bitrix-env:latest
        docker push gridorius/bitrix-env:${{github.ref_name}}
